services:
  - type: web
    plan: free
    name: File-Sharing-Bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 main.py
    repo: https://github.com/CodeXBotz/File-Sharing-Bot.git      
    branch: main
    envVars:
      - key: API_HASH 
        sync: false
      - key: APP_ID 
        sync: false
      - key: TG_BOT_TOKEN
        sync: false
      - key: OWNER_ID
        sync: false
      - key: CHANNEL_ID
        sync: false
      - key: DATABASE_URL
        sync: false 
      - key: DATABASE_NAME
        sync: false
      - key: FORCE_SUB_CHANNEL
        sync: false    
      - key: PROTECT_CONTENT
        sync: false    
    autoDeploy: false
